# Use the official Node.js image as the base image
FROM node:24-alpine AS builder

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy prisma
COPY prisma ./prisma/

# Install the application dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Prisma migrate deploy
ARG DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy?schema=public"
RUN npx prisma generate

# Build the NestJS application
RUN npm run build

# Delete devDependencies
RUN npm prune --omit=dev

# Use the official Node.js image as the base image
FROM node:24-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy the most important files
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/prisma.config.ts ./

# Expose the application port
EXPOSE 4000

# npx prisma generate && Command to run the application
# CMD ["sh", "-c", "npx prisma migrate deploy && node ./dist/src/main.js"]
CMD ["sh", "-c", "npx prisma migrate deploy && node ./dist/src/main.js"]